/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEmailsRouteImport } from './routes/_app.emails'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppSegmentsRouteImport } from './routes/_app.segments'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppContactsAccountsRouteImport } from './routes/_app.contacts.accounts'
import { Route as AppContactsListsRouteImport } from './routes/_app.contacts.lists'
import { Route as AppContactsSegmentsRouteImport } from './routes/_app.contacts.segments'
import { Route as AppContactsTagsRouteImport } from './routes/_app.contacts.tags'
import { Route as AppContactsAccountsIndexRouteImport } from './routes/_app.contacts.accounts.index'
import { Route as AppContactsAccountsIdRouteImport } from './routes/_app.contacts.accounts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsAccountsRoute = AppContactsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsListsRoute = AppContactsListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsSegmentsRoute = AppContactsSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsTagsRoute = AppContactsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsAccountsIndexRoute =
  AppContactsAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContactsAccountsRoute,
  } as any)
const AppContactsAccountsIdRoute = AppContactsAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/emails': typeof AppEmailsRoute
  '/forms': typeof AppFormsRoute
  '/segments': typeof AppSegmentsRoute
  '/settings': typeof AppSettingsRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/accounts': typeof AppContactsAccountsRouteWithChildren
  '/contacts/lists': typeof AppContactsListsRoute
  '/contacts/segments': typeof AppContactsSegmentsRoute
  '/contacts/tags': typeof AppContactsTagsRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/contacts/accounts/': typeof AppContactsAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof AppDashboardRoute
  '/emails': typeof AppEmailsRoute
  '/forms': typeof AppFormsRoute
  '/segments': typeof AppSegmentsRoute
  '/settings': typeof AppSettingsRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/lists': typeof AppContactsListsRoute
  '/contacts/segments': typeof AppContactsSegmentsRoute
  '/contacts/tags': typeof AppContactsTagsRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/contacts/accounts': typeof AppContactsAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/emails': typeof AppEmailsRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/segments': typeof AppSegmentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/contacts/accounts': typeof AppContactsAccountsRouteWithChildren
  '/_app/contacts/lists': typeof AppContactsListsRoute
  '/_app/contacts/segments': typeof AppContactsSegmentsRoute
  '/_app/contacts/tags': typeof AppContactsTagsRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/_app/contacts/accounts/': typeof AppContactsAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contacts'
    | '/dashboard'
    | '/emails'
    | '/forms'
    | '/segments'
    | '/settings'
    | '/campaigns/$id'
    | '/contacts/accounts'
    | '/contacts/lists'
    | '/contacts/segments'
    | '/contacts/tags'
    | '/campaigns/'
    | '/contacts/'
    | '/contacts/accounts/$id'
    | '/contacts/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/emails'
    | '/forms'
    | '/segments'
    | '/settings'
    | '/campaigns/$id'
    | '/contacts/lists'
    | '/contacts/segments'
    | '/contacts/tags'
    | '/campaigns'
    | '/contacts'
    | '/contacts/accounts/$id'
    | '/contacts/accounts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/emails'
    | '/_app/forms'
    | '/_app/segments'
    | '/_app/settings'
    | '/_app/campaigns/$id'
    | '/_app/contacts/accounts'
    | '/_app/contacts/lists'
    | '/_app/contacts/segments'
    | '/_app/contacts/tags'
    | '/_app/campaigns/'
    | '/_app/contacts/'
    | '/_app/contacts/accounts/$id'
    | '/_app/contacts/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emails': {
      id: '/_app/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments': {
      id: '/_app/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/accounts': {
      id: '/_app/contacts/accounts'
      path: '/accounts'
      fullPath: '/contacts/accounts'
      preLoaderRoute: typeof AppContactsAccountsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/lists': {
      id: '/_app/contacts/lists'
      path: '/lists'
      fullPath: '/contacts/lists'
      preLoaderRoute: typeof AppContactsListsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/segments': {
      id: '/_app/contacts/segments'
      path: '/segments'
      fullPath: '/contacts/segments'
      preLoaderRoute: typeof AppContactsSegmentsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/tags': {
      id: '/_app/contacts/tags'
      path: '/tags'
      fullPath: '/contacts/tags'
      preLoaderRoute: typeof AppContactsTagsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/accounts/': {
      id: '/_app/contacts/accounts/'
      path: '/'
      fullPath: '/contacts/accounts/'
      preLoaderRoute: typeof AppContactsAccountsIndexRouteImport
      parentRoute: typeof AppContactsAccountsRoute
    }
    '/_app/contacts/accounts/$id': {
      id: '/_app/contacts/accounts/$id'
      path: '/$id'
      fullPath: '/contacts/accounts/$id'
      preLoaderRoute: typeof AppContactsAccountsIdRouteImport
      parentRoute: typeof AppContactsAccountsRoute
    }
  }
}

interface AppContactsAccountsRouteChildren {
  AppContactsAccountsIdRoute: typeof AppContactsAccountsIdRoute
  AppContactsAccountsIndexRoute: typeof AppContactsAccountsIndexRoute
}

const AppContactsAccountsRouteChildren: AppContactsAccountsRouteChildren = {
  AppContactsAccountsIdRoute: AppContactsAccountsIdRoute,
  AppContactsAccountsIndexRoute: AppContactsAccountsIndexRoute,
}

const AppContactsAccountsRouteWithChildren =
  AppContactsAccountsRoute._addFileChildren(AppContactsAccountsRouteChildren)

interface AppContactsRouteChildren {
  AppContactsAccountsRoute: typeof AppContactsAccountsRouteWithChildren
  AppContactsListsRoute: typeof AppContactsListsRoute
  AppContactsSegmentsRoute: typeof AppContactsSegmentsRoute
  AppContactsTagsRoute: typeof AppContactsTagsRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsAccountsRoute: AppContactsAccountsRouteWithChildren,
  AppContactsListsRoute: AppContactsListsRoute,
  AppContactsSegmentsRoute: AppContactsSegmentsRoute,
  AppContactsTagsRoute: AppContactsTagsRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailsRoute: typeof AppEmailsRoute
  AppFormsRoute: typeof AppFormsRoute
  AppSegmentsRoute: typeof AppSegmentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailsRoute: AppEmailsRoute,
  AppFormsRoute: AppFormsRoute,
  AppSegmentsRoute: AppSegmentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
