/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDealsRouteImport } from './routes/_app.deals'
import { Route as AppEmailsRouteImport } from './routes/_app.emails'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSegmentsRouteImport } from './routes/_app.segments'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppWebsiteRouteImport } from './routes/_app.website'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppContactsAccountsRouteImport } from './routes/_app.contacts.accounts'
import { Route as AppContactsListsRouteImport } from './routes/_app.contacts.lists'
import { Route as AppContactsSegmentsRouteImport } from './routes/_app.contacts.segments'
import { Route as AppContactsTagsRouteImport } from './routes/_app.contacts.tags'
import { Route as AppDealsIndexRouteImport } from './routes/_app.deals.index'
import { Route as AppDealsIdRouteImport } from './routes/_app.deals.$id'
import { Route as AppEmailsIndexRouteImport } from './routes/_app.emails.index'
import { Route as AppEmailsArchiveRouteImport } from './routes/_app.emails.archive'
import { Route as AppEmailsTemplatesRouteImport } from './routes/_app.emails.templates'
import { Route as AppEmailsVariablesRouteImport } from './routes/_app.emails.variables'
import { Route as AppWebsiteIndexRouteImport } from './routes/_app.website.index'
import { Route as AppWebsiteFormsRouteImport } from './routes/_app.website.forms'
import { Route as AppWebsiteMessagesRouteImport } from './routes/_app.website.messages'
import { Route as AppWebsitePagesRouteImport } from './routes/_app.website.pages'
import { Route as AppWebsiteTrackingRouteImport } from './routes/_app.website.tracking'
import { Route as AppContactsAccountsIndexRouteImport } from './routes/_app.contacts.accounts.index'
import { Route as AppContactsAccountsIdRouteImport } from './routes/_app.contacts.accounts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsAccountsRoute = AppContactsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsListsRoute = AppContactsListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsSegmentsRoute = AppContactsSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsTagsRoute = AppContactsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppDealsIndexRoute = AppDealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppDealsIdRoute = AppDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDealsRoute,
} as any)
const AppEmailsIndexRoute = AppEmailsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsArchiveRoute = AppEmailsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsTemplatesRoute = AppEmailsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppEmailsVariablesRoute = AppEmailsVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => AppEmailsRoute,
} as any)
const AppWebsiteIndexRoute = AppWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteFormsRoute = AppWebsiteFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteMessagesRoute = AppWebsiteMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsitePagesRoute = AppWebsitePagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteTrackingRoute = AppWebsiteTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppContactsAccountsIndexRoute =
  AppContactsAccountsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppContactsAccountsRoute,
  } as any)
const AppContactsAccountsIdRoute = AppContactsAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/contacts': typeof AppContactsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRouteWithChildren
  '/emails': typeof AppEmailsRouteWithChildren
  '/forms': typeof AppFormsRoute
  '/reports': typeof AppReportsRoute
  '/segments': typeof AppSegmentsRoute
  '/settings': typeof AppSettingsRoute
  '/website': typeof AppWebsiteRouteWithChildren
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/accounts': typeof AppContactsAccountsRouteWithChildren
  '/contacts/lists': typeof AppContactsListsRoute
  '/contacts/segments': typeof AppContactsSegmentsRoute
  '/contacts/tags': typeof AppContactsTagsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/emails/archive': typeof AppEmailsArchiveRoute
  '/emails/templates': typeof AppEmailsTemplatesRoute
  '/emails/variables': typeof AppEmailsVariablesRoute
  '/website/forms': typeof AppWebsiteFormsRoute
  '/website/messages': typeof AppWebsiteMessagesRoute
  '/website/pages': typeof AppWebsitePagesRoute
  '/website/tracking': typeof AppWebsiteTrackingRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/deals/': typeof AppDealsIndexRoute
  '/emails/': typeof AppEmailsIndexRoute
  '/website/': typeof AppWebsiteIndexRoute
  '/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/contacts/accounts/': typeof AppContactsAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/forms': typeof AppFormsRoute
  '/reports': typeof AppReportsRoute
  '/segments': typeof AppSegmentsRoute
  '/settings': typeof AppSettingsRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/contacts/lists': typeof AppContactsListsRoute
  '/contacts/segments': typeof AppContactsSegmentsRoute
  '/contacts/tags': typeof AppContactsTagsRoute
  '/deals/$id': typeof AppDealsIdRoute
  '/emails/archive': typeof AppEmailsArchiveRoute
  '/emails/templates': typeof AppEmailsTemplatesRoute
  '/emails/variables': typeof AppEmailsVariablesRoute
  '/website/forms': typeof AppWebsiteFormsRoute
  '/website/messages': typeof AppWebsiteMessagesRoute
  '/website/pages': typeof AppWebsitePagesRoute
  '/website/tracking': typeof AppWebsiteTrackingRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/deals': typeof AppDealsIndexRoute
  '/emails': typeof AppEmailsIndexRoute
  '/website': typeof AppWebsiteIndexRoute
  '/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/contacts/accounts': typeof AppContactsAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/contacts': typeof AppContactsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deals': typeof AppDealsRouteWithChildren
  '/_app/emails': typeof AppEmailsRouteWithChildren
  '/_app/forms': typeof AppFormsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/segments': typeof AppSegmentsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/website': typeof AppWebsiteRouteWithChildren
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/contacts/accounts': typeof AppContactsAccountsRouteWithChildren
  '/_app/contacts/lists': typeof AppContactsListsRoute
  '/_app/contacts/segments': typeof AppContactsSegmentsRoute
  '/_app/contacts/tags': typeof AppContactsTagsRoute
  '/_app/deals/$id': typeof AppDealsIdRoute
  '/_app/emails/archive': typeof AppEmailsArchiveRoute
  '/_app/emails/templates': typeof AppEmailsTemplatesRoute
  '/_app/emails/variables': typeof AppEmailsVariablesRoute
  '/_app/website/forms': typeof AppWebsiteFormsRoute
  '/_app/website/messages': typeof AppWebsiteMessagesRoute
  '/_app/website/pages': typeof AppWebsitePagesRoute
  '/_app/website/tracking': typeof AppWebsiteTrackingRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/deals/': typeof AppDealsIndexRoute
  '/_app/emails/': typeof AppEmailsIndexRoute
  '/_app/website/': typeof AppWebsiteIndexRoute
  '/_app/contacts/accounts/$id': typeof AppContactsAccountsIdRoute
  '/_app/contacts/accounts/': typeof AppContactsAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/contacts'
    | '/dashboard'
    | '/deals'
    | '/emails'
    | '/forms'
    | '/reports'
    | '/segments'
    | '/settings'
    | '/website'
    | '/campaigns/$id'
    | '/contacts/accounts'
    | '/contacts/lists'
    | '/contacts/segments'
    | '/contacts/tags'
    | '/deals/$id'
    | '/emails/archive'
    | '/emails/templates'
    | '/emails/variables'
    | '/website/forms'
    | '/website/messages'
    | '/website/pages'
    | '/website/tracking'
    | '/campaigns/'
    | '/contacts/'
    | '/deals/'
    | '/emails/'
    | '/website/'
    | '/contacts/accounts/$id'
    | '/contacts/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/onboarding'
    | '/dashboard'
    | '/forms'
    | '/reports'
    | '/segments'
    | '/settings'
    | '/campaigns/$id'
    | '/contacts/lists'
    | '/contacts/segments'
    | '/contacts/tags'
    | '/deals/$id'
    | '/emails/archive'
    | '/emails/templates'
    | '/emails/variables'
    | '/website/forms'
    | '/website/messages'
    | '/website/pages'
    | '/website/tracking'
    | '/campaigns'
    | '/contacts'
    | '/deals'
    | '/emails'
    | '/website'
    | '/contacts/accounts/$id'
    | '/contacts/accounts'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/deals'
    | '/_app/emails'
    | '/_app/forms'
    | '/_app/reports'
    | '/_app/segments'
    | '/_app/settings'
    | '/_app/website'
    | '/_app/campaigns/$id'
    | '/_app/contacts/accounts'
    | '/_app/contacts/lists'
    | '/_app/contacts/segments'
    | '/_app/contacts/tags'
    | '/_app/deals/$id'
    | '/_app/emails/archive'
    | '/_app/emails/templates'
    | '/_app/emails/variables'
    | '/_app/website/forms'
    | '/_app/website/messages'
    | '/_app/website/pages'
    | '/_app/website/tracking'
    | '/_app/campaigns/'
    | '/_app/contacts/'
    | '/_app/deals/'
    | '/_app/emails/'
    | '/_app/website/'
    | '/_app/contacts/accounts/$id'
    | '/_app/contacts/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emails': {
      id: '/_app/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/segments': {
      id: '/_app/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website': {
      id: '/_app/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/accounts': {
      id: '/_app/contacts/accounts'
      path: '/accounts'
      fullPath: '/contacts/accounts'
      preLoaderRoute: typeof AppContactsAccountsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/lists': {
      id: '/_app/contacts/lists'
      path: '/lists'
      fullPath: '/contacts/lists'
      preLoaderRoute: typeof AppContactsListsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/segments': {
      id: '/_app/contacts/segments'
      path: '/segments'
      fullPath: '/contacts/segments'
      preLoaderRoute: typeof AppContactsSegmentsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/contacts/tags': {
      id: '/_app/contacts/tags'
      path: '/tags'
      fullPath: '/contacts/tags'
      preLoaderRoute: typeof AppContactsTagsRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/_app/deals/': {
      id: '/_app/deals/'
      path: '/'
      fullPath: '/deals/'
      preLoaderRoute: typeof AppDealsIndexRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/deals/$id': {
      id: '/_app/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AppDealsIdRouteImport
      parentRoute: typeof AppDealsRoute
    }
    '/_app/emails/': {
      id: '/_app/emails/'
      path: '/'
      fullPath: '/emails/'
      preLoaderRoute: typeof AppEmailsIndexRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/archive': {
      id: '/_app/emails/archive'
      path: '/archive'
      fullPath: '/emails/archive'
      preLoaderRoute: typeof AppEmailsArchiveRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/templates': {
      id: '/_app/emails/templates'
      path: '/templates'
      fullPath: '/emails/templates'
      preLoaderRoute: typeof AppEmailsTemplatesRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/emails/variables': {
      id: '/_app/emails/variables'
      path: '/variables'
      fullPath: '/emails/variables'
      preLoaderRoute: typeof AppEmailsVariablesRouteImport
      parentRoute: typeof AppEmailsRoute
    }
    '/_app/website/': {
      id: '/_app/website/'
      path: '/'
      fullPath: '/website/'
      preLoaderRoute: typeof AppWebsiteIndexRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/forms': {
      id: '/_app/website/forms'
      path: '/forms'
      fullPath: '/website/forms'
      preLoaderRoute: typeof AppWebsiteFormsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/messages': {
      id: '/_app/website/messages'
      path: '/messages'
      fullPath: '/website/messages'
      preLoaderRoute: typeof AppWebsiteMessagesRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/pages': {
      id: '/_app/website/pages'
      path: '/pages'
      fullPath: '/website/pages'
      preLoaderRoute: typeof AppWebsitePagesRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/website/tracking': {
      id: '/_app/website/tracking'
      path: '/tracking'
      fullPath: '/website/tracking'
      preLoaderRoute: typeof AppWebsiteTrackingRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/_app/contacts/accounts/': {
      id: '/_app/contacts/accounts/'
      path: '/'
      fullPath: '/contacts/accounts/'
      preLoaderRoute: typeof AppContactsAccountsIndexRouteImport
      parentRoute: typeof AppContactsAccountsRoute
    }
    '/_app/contacts/accounts/$id': {
      id: '/_app/contacts/accounts/$id'
      path: '/$id'
      fullPath: '/contacts/accounts/$id'
      preLoaderRoute: typeof AppContactsAccountsIdRouteImport
      parentRoute: typeof AppContactsAccountsRoute
    }
  }
}

interface AppContactsAccountsRouteChildren {
  AppContactsAccountsIdRoute: typeof AppContactsAccountsIdRoute
  AppContactsAccountsIndexRoute: typeof AppContactsAccountsIndexRoute
}

const AppContactsAccountsRouteChildren: AppContactsAccountsRouteChildren = {
  AppContactsAccountsIdRoute: AppContactsAccountsIdRoute,
  AppContactsAccountsIndexRoute: AppContactsAccountsIndexRoute,
}

const AppContactsAccountsRouteWithChildren =
  AppContactsAccountsRoute._addFileChildren(AppContactsAccountsRouteChildren)

interface AppContactsRouteChildren {
  AppContactsAccountsRoute: typeof AppContactsAccountsRouteWithChildren
  AppContactsListsRoute: typeof AppContactsListsRoute
  AppContactsSegmentsRoute: typeof AppContactsSegmentsRoute
  AppContactsTagsRoute: typeof AppContactsTagsRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsAccountsRoute: AppContactsAccountsRouteWithChildren,
  AppContactsListsRoute: AppContactsListsRoute,
  AppContactsSegmentsRoute: AppContactsSegmentsRoute,
  AppContactsTagsRoute: AppContactsTagsRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppDealsRouteChildren {
  AppDealsIdRoute: typeof AppDealsIdRoute
  AppDealsIndexRoute: typeof AppDealsIndexRoute
}

const AppDealsRouteChildren: AppDealsRouteChildren = {
  AppDealsIdRoute: AppDealsIdRoute,
  AppDealsIndexRoute: AppDealsIndexRoute,
}

const AppDealsRouteWithChildren = AppDealsRoute._addFileChildren(
  AppDealsRouteChildren,
)

interface AppEmailsRouteChildren {
  AppEmailsArchiveRoute: typeof AppEmailsArchiveRoute
  AppEmailsTemplatesRoute: typeof AppEmailsTemplatesRoute
  AppEmailsVariablesRoute: typeof AppEmailsVariablesRoute
  AppEmailsIndexRoute: typeof AppEmailsIndexRoute
}

const AppEmailsRouteChildren: AppEmailsRouteChildren = {
  AppEmailsArchiveRoute: AppEmailsArchiveRoute,
  AppEmailsTemplatesRoute: AppEmailsTemplatesRoute,
  AppEmailsVariablesRoute: AppEmailsVariablesRoute,
  AppEmailsIndexRoute: AppEmailsIndexRoute,
}

const AppEmailsRouteWithChildren = AppEmailsRoute._addFileChildren(
  AppEmailsRouteChildren,
)

interface AppWebsiteRouteChildren {
  AppWebsiteFormsRoute: typeof AppWebsiteFormsRoute
  AppWebsiteMessagesRoute: typeof AppWebsiteMessagesRoute
  AppWebsitePagesRoute: typeof AppWebsitePagesRoute
  AppWebsiteTrackingRoute: typeof AppWebsiteTrackingRoute
  AppWebsiteIndexRoute: typeof AppWebsiteIndexRoute
}

const AppWebsiteRouteChildren: AppWebsiteRouteChildren = {
  AppWebsiteFormsRoute: AppWebsiteFormsRoute,
  AppWebsiteMessagesRoute: AppWebsiteMessagesRoute,
  AppWebsitePagesRoute: AppWebsitePagesRoute,
  AppWebsiteTrackingRoute: AppWebsiteTrackingRoute,
  AppWebsiteIndexRoute: AppWebsiteIndexRoute,
}

const AppWebsiteRouteWithChildren = AppWebsiteRoute._addFileChildren(
  AppWebsiteRouteChildren,
)

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRouteWithChildren
  AppEmailsRoute: typeof AppEmailsRouteWithChildren
  AppFormsRoute: typeof AppFormsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSegmentsRoute: typeof AppSegmentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWebsiteRoute: typeof AppWebsiteRouteWithChildren
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRouteWithChildren,
  AppEmailsRoute: AppEmailsRouteWithChildren,
  AppFormsRoute: AppFormsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSegmentsRoute: AppSegmentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWebsiteRoute: AppWebsiteRouteWithChildren,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
